### PR TITLE
Aragon Nest Proposal: Decentralized Autonomous Licence

### PR DESCRIPTION
**Pull request by rouxel**
# Aragon Nest Proposal  : Production of a licence entitled  Decentralized Autonomous Licence which aims to protect contents create by DAOs and which allows DAO to collectively define the rules and organizational parameters of a content-DAO. #48

## Abstract

The goal of RyhopeLab is to offer a full set of « licences » inspired from Free and Open Source Licenses (or similar licenses like the IANG License or PPL – Peer Production Licence) specifically “augmented” and designed to support DAOs in their self-governance. This project of licence aims to  help the content-DAO - content-DAO meaning : a DAO organized around content such as video-games, software, books, etc -  in defining the modalities of collective decision making, value sharing, and the types of possible utilization of the creative collaborative content outside the blockchain ecosystem. The final objective of our team is therefore to provide freely usable contractual frameworks, as standards, allowing DAOs to collectively define the terms of use and governance of collaborative creative contents. The goal of this project is to design a full set of licences implementing an isomorphism between DAOs governance rules - as defined through blockchain-based smart contracts - and nation-states juridical frameworks.

## Deliverables

1. A licence called Decentralized Autonomous Licence whose legal code is authoritative in the field of creation law and which is specifically designed to accompany DAOs in contact with traditional law.
2. A dynamic license operating as a standard and wich clearly defines for each DAO the rules and parameters attached to the collaborative production of creative contents such as software, music, book and so on.

## Grant size

80-90 K for:
40K - Payment of lawyers and other team members for writing legal licenses
10K - Travel and expenses of the project members to organize the communication of those licenses to the actors of open-source movement and blockchain ecosystem.
40K - Development and implementation of smarts-contracts

50K bonus - In the case success of the project through deployment and effective use of this license.

## Application requirements

Project specifics included in research paper bellow :
https://docs.google.com/document/d/1tYNMLkKpeSbPuPhusqw6LyUCIy08KeZFmv2KrylOPS4/edit?usp=sharing

## Legal structure
No legal structure

### CODE REVIEW

**Comment by mariapao** [comment]
Hi @rouxel thank you for submitting such an interesting application. 

After having reviewed it, we have the following questions:

1. Can you elaborate more on how this solution would work in practice? You say: in the case of disputes unsettable neither in the framework of the DAOs governance nor in the one of the upcoming Aragon Network Jurisdiction, DAOs could immediately profit from nation-state jurisdictions. I imagine in this case we will have a legal contract (the license) to work with in the traditional legal system. But, who represents the DAO before a court, any member? And this question brings us to the issue of whether the members of the DAO would be subject to KYC/AML requirements in order for the license to be considered valid? Also, would the members be subject to KYC/AML requirements in order to earn royalties? The licensees are all members of the DAO?

2.  When you talk about the hypothesis of this approach you talk about the benefits of having DAOs express their legal status within the scope of IP rights. What would be the tradeoffs and limitations of this approach? 

3. Can you elaborate a bit more on the contractual framework you would be delivering? As per page 10 of the research paper, the framework comprises 4 layers: 1. Legal code and smart contracts, 2. Readable by human (radspec), 3. Machine readable and AragonOS compatible, 4. Values of DAO parameters editable by humans. Can you elaborate on each part of the framework a bit more? 

We imagine you are thinking of some sort of ricardian contract with the legal text referencing dynamic values on chain? For example, the rights of holders to this license are defined by the balances of tokens at a specified address. Or you would have a version of the contracts that can reference the token manager. What exactly do you mean when you say the license will be aragonOS compatible? Are we going to have an app on Aragon? 

4. How forks of projects would work from a license perspective?

5.  You say to build the license you will start from the bases laid down by the PPL. This license doesn't exclude commercial entities but if they would seek to make a profit by using the common good these entities could only do so by contributing financially to the maintenance of the common. I was wondering if you guys have read [this](https://medium.com/hive-commons/harberger-taxation-and-open-source-58dcdbab140d) post by Luke. Is the solution that Luke is proposing in this post, something close to what you have n mind? Also, what are your thoughts around license compatibility issues and adoption? Does the p2p foundation have an approval process for new licenses?

6. You say the use of the license/governance framework would radically ease the interoperability - and thus the possibility of much more complex cross interactions between DAOs. Can you elaborate more on the interoperability? I imagine the vision is a smart contract/legal framework that everybody would use to create and govern their DAO? 

7. Regarding the milestones, can you be a bit more specific or give us a bit more of detail about what each deliverable would entail? For example, what the first phase of legal rewriting would comprise? What the organization of community effort would entail? How would you reach the collective definition of the parameters desired by the community? and so on.

**Comment by rouxel** [comment]
Hi @mariapao 

Thank you very much for that very precise feedback !  We will write a document to answer all your questions ASAP. We are bringing the entire research team together this weekend to discuss all of this.

Best

**Comment by mariapao** [comment]
Hi @rouxel how are you guys doing with doc? I just wanted to follow up on this.

**Comment by mariapao** [comment]
Hi @rouxel thanks for the update! Looking forward to seeing the doc and the mock-up of the API

**Comment by rouxel** [comment]
Hello Maria.

Sorry for the length of the return the lawyers were absent and I took the time to enter into discussion with the P2P foundation via Michel Bauwens and the P2P laboratory.

You will therefore find below answers to your questions:

https://docs.google.com/document/d/1LfJX3dYj-pm1G7bSocEzYlPbT4Pppkc5nkV-lTLAp2U/edit?usp=sharing

Hoping that you will be interested.

Best

**Comment by mariapao** [comment]
Hi @rouxel as per our previous conversations regarding the potential new flock team: Aragon Black, of which you would be part of and given the possibility that this project might continue under the wind of such new team, I'm closing this PR for the moment.

**Pull request closed without merging**
