### PR TITLE
Research Into Best Practice for Decentralised Teams

### PR DESCRIPTION
**Pull request by epocket**
# Request for Nest membership and funding (#1)

**Team name**: Iain Barclay

**Burn rate**: $1083/month ($3250/quarter)

**Legal structure**: NA / Individual

## Proposal

I have an unconditional offer to study for an MPhil research degree at Cardiff University, UK, over 2 years commencing in April 2018.

The outline of the proposed research is to study organisations and groups which operate in a decentralised manner, and to try to determine whether the rules and processes by which they operate could be coded into best practice using smart contracts and deployed on a blockchain. Through case-study and implementation of smart contracts, I will provide recommendations on the feasibility and best practice for using blockchain-based DAO’s to govern organisations.

The research would review material on distributed organizational structure, including Holacracies and Teal Organisations, as well as case studies on groups which operate in a decentralised way in order that we can start to distill some of the processes which we may encode in the DAO contracts. This would include emergent groups and citizen teams which form both locally and remotely during disaster or emergency situations, and groups which have formed to work together in fields including open source software, Wikipedia curation, and the sharing economies.

For this project, I would propose to use Aragon for the implementation phase of the study.

## Deliverables

1. A published research paper outlining the literature review and results of the study.
2. A guide to “Best Practise” for decentralised teams and organisations using blockchain/DAO structures.
3. A code implementation of the best practise recommendations.

## Grant size

Funding: $26,000 in ETH, paid quarterly over two years.

Based on 1 person paid at UK university stipend rate, 2 years part-time = £14,296
University Fees for 2 years = £4200

Success reward: Up to $15k in ANT, given out when all deliverables are complete.

## Application requirements

Please find enclosures (in grants directory)
- Research Proposal submitted/accepted by Cardiff University.
- team.md
- roadmap.md

## Development timeline
To be determined in conjunction with the University and Aragon sponsors when research commences, but to include quarterly progress reports, interim deliverables and final deliverables by March 2020.

### CODE REVIEW

**Comment by renexdev** [comment]
26000/2./4. = 3250... meaning a burning rate of $3250/quarter not monthly...

**Comment by verdverm** [comment]
@epocket you may find this interesting: [Ethereum Research topics](http://notes.eth.sg/s/rkxpeG0ff) (If you haven't seen it)

**Comment by epocket** [comment]
@mariapao - I'm just checking with the university that the CLA doesn't conflict with any other conditions, hopefully they will respond soon and I can sign...

**Comment by mariapao** [comment]
@epocket I see no issue now.

**Comment by mariapao** [comment]
I'm closing this pull request.

**Comment by epocket** [comment]
Thanks @mariapao - appreciate your time and kind words, I just dropped you an email to connect for future communications. Thanks again, and best wishes to you and the team.

**Pull request closed without merging**
